class RouteName {
  static const splash = '/';
  static const login = '/login';
  static const forgotPassword = '/forgot-password';
  static const home = '/home';
  static const attendance = '/attendance';
  static const checkInVerification = '/attendance/check-in/verification';
  static const checkInLoading = '/attendance/check-in/loading';
  static const checkInConfirmation = '/attendance/check-in/confirmation';
  static const checkInSuccess = '/attendance/check-in/success';
  static const checkOutVerification = '/attendance/check-out/verification';
  static const checkOutLoading = '/attendance/check-out/loading';
  static const checkOutConfirmation = '/attendance/check-out/confirmation';
  static const checkOutSuccess = '/attendance/check-out/success';
  static const leave = '/leave';
  static const leaveApply = '/leave/apply';
  static const leaveConfirmation = '/leave/confirmation';
  static const leaveStatus = '/leave/status';
  static const leaveSuccess = '/leave/success';
  static const leaveCancel = '/leave/cancel';
  static const leaveCancelSuccess = '/leave/cancel/success';
  static const leaveHistory = '/leave/history';
  static const emergency = '/emergency';
  static const emergencyDispensation = '/emergency/dispensation';
  static const emergencyDispensationConfirmation =
      '/emergency/dispensation/confirmation';
  static const emergencyDispensationSuccess = '/emergency/dispensation/success';
  static const emergencyLeave = '/emergency/leave';
  static const emergencyLeaveConfirmation = '/emergency/leave/confirmation';
  static const emergencyHistory = '/emergency/history';
  static const notification = '/notification';
  static const notificationDetail = '/notification/detail';
  static const profile = '/profile';
  static const changePassword = '/profile/change-password';
  static const history = '/history';
  static const managerLeaveApprovals = '/manager/leave-approvals';
  static const managerLeaveApprovalDetail = '/manager/leave-approvals/detail';
  static const managerLeaveRejectReason = '/manager/leave-approvals/reject';
}
